# Shared constants for multiagent-firewall
# Prompts usable by the LLM detector agent and their locations under prompts/
LLM_PROMPT_MAP = {
    "zero-shot": "zero-shot.txt",
    "enriched-zero-shot": "enriched-zero-shot.txt",
    "few-shot": "few-shot.txt",
}

# Regex patterns for DLP detection agent
REGEX_PATTERNS = {
    "SSN": r"\b\d{3}[\s\-]?\d{2}[\s\-]?\d{4}\b",
    "EMAIL": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
    "PHONENUMBER": r"\b\+?\d[\d\s\-\(\)]{7,}\d\b",
    "CREDITCARDNUMBER": r"\b(?:\d{4}[\s\-]?){3}\d{4}\b",
    "CREDITCARDCVV": r"\b\d{3,4}\b",
    "IPV4": r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b",
    "IPV6": r"\b(?:[A-Fa-f0-9]{1,4}:){7}[A-Fa-f0-9]{1,4}\b|(?:[A-Fa-f0-9]{1,4}:){1,7}:|(?:[A-Fa-f0-9]{1,4}:){1,6}:[A-Fa-f0-9]{1,4}\b",
    "MAC": r"\b(?:[0-9A-Fa-f]{2}[:\-]){5}[0-9A-Fa-f]{2}\b",
    "IBAN": r"\b[A-Z]{2}\d{2}[A-Z0-9]{4}\d{7}([A-Z0-9]?){0,16}\b",
    "BIC": r"\b[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b",
    "URL": r"\b(?:https?|ftp)://[^\s/$.?#].[^\s]*\b",
    "DNI": r"\b\d{8}[A-Z]\b",
    "PASSPORTNUMBER": r"\b[A-Z]{1,2}\d{6,9}\b",
    "BITCOINADDRESS": r"\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b|bc1[a-z0-9]{39,59}\b",
    "ETHEREUMADDRESS": r"\b0x[a-fA-F0-9]{40}\b",
    "LITECOINADDRESS": r"\b[LM3][a-km-zA-HJ-NP-Z1-9]{26,33}\b",
    "ZIPCODE": r"\b\d{5}(?:[\-\s]\d{4})?\b",
    "DATE": r"\b(?:\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}|\d{4}[\/\-\.]\d{1,2}[\/\-\.]\d{1,2})\b",
    "TIME": r"\b(?:[01]?\d|2[0-3]):[0-5]\d(?::[0-5]\d)?\b",
    "VEHICLEVIN": r"\b[A-HJ-NPR-Z0-9]{17}\b",
    "PIN": r"\b\d{4,6}\b",
}

# Keyword lists for DLP detection agent
KEYWORDS = {
    "SSN": ["ssn", "social security", "social security number", "social"],
    "DNI": ["dni", "documento nacional de identidad", "national identity document"],
    "PASSPORTNUMBER": ["passport", "passport number", "passport #", "passport no"],
    "CREDITCARDNUMBER": ["credit card", "card number", "cc number", "card #"],
    "CREDITCARDCVV": ["cvv", "cvc", "security code", "card security"],
    "APIKEY": ["api_key", "apikey", "api-key", "api key", "x-api-key"],
    "SECRET": ["secret", "client_secret", "secret_key"],
    "PASSWORD": ["password", "pwd", "passwd", "pass"],
    "TOKEN": ["token", "bearer", "auth", "access_token", "auth_token", "jwt"],
    "CREDENTIALS": ["credentials", "login", "username and password"],
    "IP": ["ip address", "ip addr", "host"],
    "IPV4": ["ipv4", "ip address"],
    "IPV6": ["ipv6"],
    "MAC": ["mac address", "physical address", "hardware address"],
    "IBAN": ["iban", "international bank account"],
    "BIC": ["bic", "swift", "swift code", "swift/bic"],
    "ACCOUNTNUMBER": ["account number", "account #", "bank account"],
    "PIN": ["pin", "pin code", "personal identification number"],
    "GENETICDATA": ["genetic", "dna", "genome", "genetic information"],
    "BIOMETRICDATA": ["biometric", "fingerprint", "facial recognition", "iris scan", "retina"],
    "HEALTHDATA": ["medical", "health record", "diagnosis", "prescription", "patient"],
    "CRIMINALRECORD": ["criminal record", "conviction", "arrest record", "police record"],
    "CONFIDENTIALDOC": ["confidential", "classified", "restricted", "proprietary", "internal only"],
    "EMAIL": ["email", "e-mail", "mail"],
    "PHONENUMBER": ["phone", "telephone", "mobile", "cell"],
    "PHONEIMEI": ["imei", "device identifier"],
    "URL": ["url", "website", "link", "http"],
    "CLIENTDATA": ["client", "customer data", "customer information"],
    "EMPLOYEEDATA": ["employee", "staff", "personnel"],
    "SALARYDETAILS": ["salary", "wage", "compensation", "pay", "remuneration"],
    "COMPANYNAME": ["company", "corporation", "organization", "firm"],
    "USERNAME": ["username", "user", "login name", "account name"],
    "STREET": ["street", "address", "avenue", "road", "boulevard"],
    "CITY": ["city", "town", "municipality"],
    "STATE": ["state", "province", "region"],
    "ZIPCODE": ["zip", "postal code", "postcode"],
    "BITCOINADDRESS": ["bitcoin", "btc address", "btc"],
    "ETHEREUMADDRESS": ["ethereum", "eth address", "eth"],
    "LITECOINADDRESS": ["litecoin", "ltc address", "ltc"],
    "DOB": ["date of birth", "dob", "birth date", "birthdate"],
    "VEHICLEVIN": ["vin", "vehicle identification number", "chassis number"],
    "VEHICLEVRM": ["license plate", "registration plate", "vrm", "plate number"],
    "SOCIALMEDIAHANDLE": ["twitter", "instagram", "facebook", "@", "social media"],
    "CV": ["cv", "resume", "curriculum vitae"],
}

# Defines the scoring value each detected field category sums
RISK_SCORE = {
    "high": 6,
    "medium": 2,
    "low": 1,
}

# Defines the threshold to calculate global risk value based on the sum of all detected fields.
RISK_SCORE_THRESHOLDS = {
    "high": 6,
    "medium": (4, 5),
    "low": (1, 3),
}

# Risk level field sets
HIGH_RISK_FIELDS = {
    "PASSWORD",
    "CREDENTIALS",
    "SSN",
    "DNI",
    "PASSPORTNUMBER",
    "CREDITCARDNUMBER",
    "IP",
    "IPV4",
    "IPV6",
    "MAC",
    "CREDITCARDCVV",
    "ACCOUNTNUMBER",
    "IBAN",
    "PIN",
    "GENETICDATA",
    "BIOMETRICDATA",
    "STREET",
    "VEHICLEVIN",
    "HEALTHDATA",
    "CRIMINALRECORD",
    "CONFIDENTIALDOC",
    "LITECOINADDRESS",
    "BITCOINADDRESS",
    "ETHEREUMADDRESS",
    "PHONEIMEI",
    "APIKEY",
    "SECRET",
    "TOKEN",
}

MEDIUM_RISK_FIELDS = {
    "EMAIL",
    "PHONENUMBER",
    "URL",
    "CLIENTDATA",
    "EMPLOYEEDATA",
    "SALARYDETAILS",
    "COMPANYNAME",
    "JOBTITLE",
    "JOBTYPE",
    "JOBAREA",
    "ACCOUNTNAME",
    "PROJECTNAME",
    "CODENAME",
    "EDUCATIONHISTORY",
    "CV",
    "SOCIALMEDIAHANDLE",
    "SECONDARYADDRESS",
    "CITY",
    "STATE",
    "COUNTY",
    "ZIPCODE",
    "BUILDINGNUMBER",
    "USERAGENT",
    "VEHICLEVRM",
    "NEARBYGPSCOORDINATE",
    "BIC",
    "MASKEDNUMBER",
    "AMOUNT",
    "CURRENCY",
    "CURRENCYSYMBOL",
    "CURRENCYNAME",
    "CURRENCYCODE",
    "CREDITCARDISSUER",
    "USERNAME",
    "INFRASTRUCTURE",
}

LOW_RISK_FIELDS = {
    "PREFIX",
    "FIRSTNAME",
    "MIDDLENAME",
    "LASTNAME",
    "AGE",
    "DOB",
    "GENDER",
    "SEX",
    "HAIRCOLOR",
    "EYECOLOR",
    "HEIGHT",
    "WEIGHT",
    "SKINTONE",
    "OTHER FEATURES",
    "RACIALORIGIN",
    "RELIGION",
    "POLITICALOPINION",
    "PHILOSOPHICALBELIEF",
    "TRADEUNION",
    "DATE",
    "TIME",
    "ORDINALDIRECTION",
    "SEXUALORIENTATION",
    "CHILDRENDATA",
    "LEGALDISCLOSURE",
}
